name: lambda_calculus
description:
  A library for lambda calculus. It supports parsing and evaluating lambda terms
  with different strategies. It also has preliminary support for type inference.
version: 1.2.0
repository: https://github.com/MMZK1526/lambda_calculus

environment:
  sdk: ^3.0.3

# Add regular dependencies here.
dependencies:
  collection: ^1.17.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.1
