name: lambda_calculus
description: A library for lambda calculus.
version: 1.0.0
repository: https://github.com/MMZK1526/lambda_calculus

environment:
  sdk: ^3.0.3

# Add regular dependencies here.
dependencies:
  dartz: ^0.10.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.1
